_setstate_noncurrent():  New assert.  Hoping to get closer to the true cause of the:
  TypeError: unpack() argument 2 must be string or read-only buffer, not None

failure often seen in overnight testrunner reports now, coming from the
checkConcurrentUpdatesInVersions test.  If the hypothesis is correct,
we'll see a failure of the new

        assert end is not None

instead.


git-svn-id: svn://svn.zope.org/repos/main@3516 62d5b8a3-27da-0310-9561-8e5933582275