Move to ZODB 3.6.0a4 (it's been a month since Zope3 got the latest ZODB, and bugfixes have been accumulating).
I see two test glitches, but those were present before
the ZODB stitch:

On Linux and Windows, at the end of the functional tests:

"""
The following test left garbage:
C:\Code\Zope3\src\zwiki\browser\browser.txt
[<socket._fileobject object at 0x08F8C110>]
"""

On Windows using Python 2.4.2, in the unit tests:

"""
File "C:\Code\Zope3\src\zope\testing\profiling.txt", line 35, in profiling.txt
Failed example:
    testrunner.run(defaults)
Exception raised:
    Traceback (most recent call last):
      File "C:\Code\Zope3\src\zope\testing\doctest.py", line 1256, in __run
        compileflags, 1) in test.globs
      File "<doctest profiling.txt[8]>", line 1, in ?
        testrunner.run(defaults)
      File "C:\Code\Zope3\src\zope\testing\testrunner.py", line 186, in run
        os.unlink(file_name)
    OSError: [Errno 13] Permission denied: 'tests_profile.jwerjh.prof'
"""

That's due to Windows-specific bugs in the zope.testing snapshot Zope3
is using (which have since been fixed on the zope.testing trunk).


git-svn-id: svn://svn.zope.org/repos/main@38898 62d5b8a3-27da-0310-9561-8e5933582275