Emit a sensible error message if you use provideAdapter incorrectly.
I had written code like this

  zope.component.provideAdapter(myAdapter, adapts=IFoo, provides=IBar)

and got a completely incomprehensible error message

  TypeError: ('__getitem__', <InterfaceClass zope.interface.interfaces.IInterface>)

because '__getitem__' happened to be the first name returned by list(IFoo).
After my checkin the error message will say

  TypeError: the required argument should be a list of interfaces, not a single interface



git-svn-id: svn://svn.zope.org/repos/main@40441 62d5b8a3-27da-0310-9561-8e5933582275