When ContentsPage.allowSearch is set to False, ContentsPage.searchForm is left as None. contents.pt was calling render on ContentsPage.searchForm whether allowSearch was true or false. This was causing a:
TraversalError: (None, 'render')

Add a tal:condition in contents.pt to the fieldset where searchForm was rendered to avoid the error.



git-svn-id: svn://svn.zope.org/repos/main@87629 62d5b8a3-27da-0310-9561-8e5933582275